# Generated by Django 3.1.7 on 2021-03-19 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drugs', '0002_auto_20210312_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indication',
            name='indication_text',
            field=models.CharField(max_length=25),
        ),
    ]
