# Generated by Django 3.1.7 on 2021-03-12 16:16

from django.db import migrations, models
from django.contrib.postgres.fields import JSONField


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compounds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compound_text', models.CharField(max_length=100)),
                ('pub_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Indications',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('indication_text', models.CharField(max_length=5)),
                ('pub_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_text', models.CharField(max_length=20)),
                ('pub_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Targets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_text', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(verbose_name='date Published')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Similarity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('user_id', models.CharField(max_length=10)),
                ('image_id', models.CharField(max_length=10)),
                ('similarity', models.FloatField()),
                ('smile', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prediction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', JSONField()),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
